name: Release

on:
  push:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            asset: linux-x86_64
            build-path: build/x86_64-unknown-linux-gnu/release/install/t
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Rust Cache
        uses: Swatinem/rust-cache@v1.2.0
        with:
          key: cache-v1
      - name: Set up Python
        uses: actions/setup-python@v2.2.2
        with:
          # Canonical definition of the version of Python that will be used
          # for the tool inside the Rust container. Must be a version available
          # at <https://github.com/indygreg/python-build-standalone/releases>.
          python-version: 3.8.9
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install PyOxidizer
        run: |
          # Use the main branch as it has unreleased features. PyOxidizer aims
          # to maintain strong backwards compatibility and stability on the
          # main branch.
          cargo install \
            --git https://github.com/indygreg/PyOxidizer.git \
            --branch main \
            pyoxidizer
      - name: Build
        run: VERSION="v${{ github.run_number }}" pyoxidizer build --release
      - name: Upload build
        uses: actions/upload-artifact@v2.2.3
        with:
          name: ${{ matrix.asset }}
          path: ${{ matrix.build-path }}
          if-no-files-found: error
          retention-days: 1
  release:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download linux build
        uses: actions/download-artifact@v2.0.9
        with:
          name: linux-x86_64
      - name: Tag release
        run: |
          git tag v${{ github.run_number }}
          git push --tags
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release v${{ github.run_number }}
          prerelease: true
          tag_name: v${{ github.run_number }}
          files: |
            linux-x86_64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
